### ISSUE TITLE
Angular Folder Structure

### ISSUE THREAD

**Issue by TomHAnderson** [DanWahlin/angular-architecture#40]
Hello,

Because your project is active (last update = 2 weeks) I wanted to make you aware of another project with the same goals:  https://github.com/mathisGarberg/angular-folder-structure

We have extensive documentation and the application is undergoing something of a makeover right now.  I invite you to explore our project and look forward to hearing from you.

**Comment by DanWahlin** [comment]
Thanks - appreciate the info. I'll check it out.
